### ISSUE TITLE
Publish CurateND policies

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#229] opened 2015-10-08 15:40 UTC
CurateND has several policies. They should be published in CurateND at `/policies` and be available at a URI (anchors are fine, individual pages are better).

---
[Trello Card](https://trello.com/c/yW8f7oGK)

**Comment by jeremyf** [comment] 2015-10-08 15:46
Duplicate of #228

**Closed by jeremyf** 2015-10-08 15:46 UTC
